import {readFileSync,writeFileSync,mkdirSync,rmSync,cpSync} from "node:fs";
import {join} from "node:path";
const root=new URL("../",import.meta.url).pathname,out=join(root,"pages-dist");rmSync(out,{recursive:true,force:true});mkdirSync(out,{recursive:true});
let source=readFileSync(join(root,"app/guide/docs.ts"),"utf8");source=source.replace(/^export type[^\n]+\n/,"").replace("export const docs:Doc[]=","const docs=").replace(/\nexport const getDoc[\s\S]*$/,"");const docs=Function(`${source};return docs`)();
const esc=s=>s.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");
const href=(scope,d)=>scope==="root"?(d.slug==="concepts"?"guide/index.html":`guide/${d.slug}/index.html`):scope==="shallow"?(d.slug==="concepts"?"index.html":`${d.slug}/index.html`):(d.slug==="concepts"?"../index.html":`../${d.slug}/index.html`);
const top=(prefix,active="docs")=>`<header class="topbar"><a class="brand" href="${prefix}index.html">AI-NATIVE SDLC</a><nav aria-label="主导航"><a class="${active==="product"?"active":""}" href="${prefix}index.html">产品</a><a class="${active==="docs"?"active":""}" href="${prefix}guide/index.html">文档</a><a href="${prefix}guide/templates/index.html">模板</a><a href="${prefix}guide/sources/index.html">来源</a></nav></header>`;
const head=(title,description,prefix)=>`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><meta name="description" content="${description}"><meta property="og:title" content="${title}"><meta property="og:description" content="${description}"><meta property="og:image" content="https://huiyonghkw.github.io/ai-native-sdlc-guide/og.png"><meta name="twitter:card" content="summary_large_image"><link rel="stylesheet" href="${prefix}assets/styles.css"></head><body>`;
const footer=`<footer class="footer docs-footer shell"><p>会勇禾口王的 AI 笔记 · @huiyonghkw</p><p>非官方中文学习手册 · 请以英文原文为准</p></footer>`;
const sidebar=(current,scope)=>`<aside class="sidebar" aria-label="文档目录"><p>中文手册</p>${docs.map(d=>`<a class="${d.slug===current?"current":""}" href="${href(scope,d)}"><span>${d.number}</span>${d.title.split("：")[0]}</a>`).join("")}<div class="sidebar-source"><small>英文原文</small><a href="https://claude.com/blog/the-ai-native-sdlc-playbook">Claude · 2026-08-21 ↗</a></div></aside>`;
const section=(s,i)=>`<section class="doc-section"><div class="section-index">${String(i+1).padStart(2,"0")}</div><div><h2>${s.heading}</h2>${(s.paragraphs||[]).map(p=>`<p>${p}</p>`).join("")}${s.bullets?`<ul>${s.bullets.map(x=>`<li>${x}</li>`).join("")}</ul>`:""}${s.code?`<pre><code>${esc(s.code)}</code></pre>`:""}${s.note?`<aside class="note"><b>注意</b><p>${s.note}</p></aside>`:""}</div></section>`;
for(const [i,d] of docs.entries()){const shallow=d.slug==="concepts",scope=shallow?"shallow":"doc",prefix=shallow?"../":"../../";const dir=shallow?join(out,"guide"):join(out,"guide",d.slug);mkdirSync(dir,{recursive:true});const prev=docs[i-1],next=docs[i+1];const pager=`<nav class="pager">${prev?`<a href="${href(scope,prev)}"><small>上一篇</small><b>← ${prev.title}</b></a>`:"<span></span>"}${next?`<a href="${href(scope,next)}"><small>下一篇</small><b>${next.title} →</b></a>`:"<span></span>"}</nav>`;const html=head(`${d.title} · AI 原生 SDLC 中文手册`,d.summary,prefix)+top(prefix)+`<div class="docs-shell">${sidebar(d.slug,scope)}<article class="doc"><div class="crumb"><a href="${prefix}index.html">首页</a><span>/</span><a href="${shallow?"index.html":"../index.html"}">文档</a><span>/</span>${d.title}</div><p class="doc-kicker">${d.number} · ${d.kicker}</p><h1>${d.title}</h1><p class="doc-summary">${d.summary}</p>${d.sections.map(section).join("")}${pager}</article></div>${footer}</body></html>`;writeFileSync(join(dir,"index.html"),html)}
const cards=docs.slice(1,7).map(d=>`<a class="stage-card" href="${href("root",d)}"><span class="stage-no">${d.number}</span><h3>${d.title.split("：")[0]}</h3><p>${d.summary}</p><b>阅读 →</b></a>`).join("");
const home=head("AI 原生 SDLC 中文手册","完整理解 Anthropic AI-Native SDLC playbook 的非官方中文学习手册。","")+top("","product")+`<main><section class="hero shell"><div class="eyebrow"><span class="signal"></span>非官方中文学习手册 · 2026</div><h1>代码写快以后，<br><span>研发流程反而堵了。</span></h1><p class="lede">Anthropic 的 AI 原生软件开发生命周期，真正改造的不是一段代码，而是计划、设计、构建、测试、部署和维护之间的整条交接链。</p><div class="actions"><a class="primary" href="guide/index.html">开始阅读</a><a class="secondary" href="https://claude.com/blog/the-ai-native-sdlc-playbook">核对英文原文</a></div><div class="bottleneck"><div><small>旧瓶颈</small><strong>BUILD</strong><span>人工写代码</span></div><i>→</i><div class="hot"><small>新瓶颈</small><strong>PLAN · TEST · DEPLOY</strong><span>交接、验证与批准</span></div></div></section><section class="section shell"><div class="section-head"><span>THE LOOP</span><h2>六个阶段，一条能回流的产物链</h2></div><div class="stage-grid">${cards}</div></section><section class="artifact shell"><div><span>COMMITTED ARTIFACTS</span><h2>聊天会结束，产物必须留下来</h2><p>每一阶段都写下一个人和智能体都能读取的版本化产物。提交记录保存谁提出、谁修改、谁批准，以及下一步为什么被触发。</p></div><ol><li><code>intent.md</code><em>问题与结果</em></li><li><code>spec.md</code><em>需求与约束</em></li><li><code>plan.md</code><em>文件、顺序、验证</em></li><li><code>diff + tests</code><em>实现与证据</em></li><li><code>PR + incident</code><em>批准与回流</em></li></ol></section></main>${footer}</body></html>`;writeFileSync(join(out,"index.html"),home);mkdirSync(join(out,"assets"),{recursive:true});writeFileSync(join(out,"assets/styles.css"),readFileSync(join(root,"app/globals.css"),"utf8").replace('@import "tailwindcss";',''));writeFileSync(join(out,".nojekyll"),"");try{cpSync(join(root,"public/og.png"),join(out,"og.png"))}catch{}console.log(`Built ${docs.length+1} static pages in pages-dist`);
