import Link from "next/link";
import {docs,Doc} from "./docs";

export function DocsShell({doc,children}:{doc:Doc;children:React.ReactNode}){
 const i=docs.findIndex(d=>d.slug===doc.slug),prev=docs[i-1],next=docs[i+1];
 return <main><header className="topbar"><Link className="brand" href="/">AI-NATIVE SDLC</Link><nav aria-label="主导航"><Link href="/">产品</Link><Link className="active" href="/guide">文档</Link><Link href="/guide/templates">模板</Link><Link href="/guide/sources">来源</Link></nav></header><div className="docs-shell"><aside className="sidebar" aria-label="文档目录"><p>中文手册</p>{docs.map(x=><Link className={x.slug===doc.slug?"current":""} href={x.slug==="concepts"?"/guide":`/guide/${x.slug}`} key={x.slug}><span>{x.number}</span>{x.title.split("：")[0]}</Link>)}<div className="sidebar-source"><small>英文原文</small><a href="https://claude.com/blog/the-ai-native-sdlc-playbook">Claude · 2026-08-21 ↗</a></div></aside><article className="doc"><div className="crumb"><Link href="/">首页</Link><span>/</span><Link href="/guide">文档</Link><span>/</span>{doc.title}</div><p className="doc-kicker">{doc.number} · {doc.kicker}</p><h1>{doc.title}</h1><p className="doc-summary">{doc.summary}</p>{children}<nav className="pager">{prev?<Link href={prev.slug==="concepts"?"/guide":`/guide/${prev.slug}`}><small>上一篇</small><b>← {prev.title}</b></Link>:<span/>}{next?<Link href={`/guide/${next.slug}`}><small>下一篇</small><b>{next.title} →</b></Link>:<span/>}</nav></article></div><footer className="footer docs-footer shell"><p>会勇禾口王的 AI 笔记 · @huiyonghkw</p><p>非官方中文学习手册 · 请以英文原文为准</p></footer></main>
}

export function DocBody({doc}:{doc:Doc}){return <>{doc.sections.map(s=><section className="doc-section" key={s.heading}><h2>{s.heading}</h2>{s.paragraphs?.map(p=><p key={p}>{p}</p>)}{s.bullets&&<ul>{s.bullets.map(x=><li key={x}>{x}</li>)}</ul>}{s.code&&<pre><code>{s.code}</code></pre>}{s.note&&<aside className="note"><b>注意</b><p>{s.note}</p></aside>}</section>)}</>}
